%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (GetVal)
%;**     Description :
%;**         Get the state of the buttons
%include Common\GeneralParameters.inc (27)
%;**       * But1%ParBut1 %>27 - State of the Button 1 - TRUE = pressed
%;**       * But2%ParBut2 %>27 - State of the button 2 - TRUE = pressed
%include Common\GeneralReturnNothing.inc
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine